(autoload 'gse-rename                           "gse-rename" "" t)
(autoload 'gse-rename-fast                      "gse-rename" "" t)
(autoload 'gse-rename-mode                      "gse-rename" "" t)
(autoload 'gse-rename-setup                     "gse-rename" "" nil)
(autoload 'gse-rename-gnu-emacs-directory-files "gse-rename" "" nil)
(autoload 'gse-rename-directory-files           "gse-rename" "" nil)
(autoload 'gse-rename-go                        "gse-rename" "" t)
(autoload 'gse-rename-script                    "gse-rename" "" t)
(provide 'gse-rename-autoloads)
